import {v4 as uuid} from "uuid";

export const products = [
    {
        _id: uuid(),
        name: "Men Checked Shirt1",
        alt: "mens shirt",
        brand: "Roadster",
        newPrice: 1750,
        oldPrice: 2499,
        discount: 67,
        size: "L",
        idealFor: "M",
        rating: 4.2,
    },
    {
        _id: uuid(),
        name: "Men Checked Shirt2",
        alt: "mens shirt",
        brand: "Roadster",
        newPrice: 700,
        oldPrice: 2000,
        discount: 35,
        size: "L",
        idealFor: "M",
        rating: 4.2,
    },
    {
        _id: uuid(),
        name: "Men Checked Shirt3",
        alt: "mens shirt",
        brand: "Roadster",
        newPrice: 1589,
        oldPrice: 2399,
        discount: 30,
        size: "L",
        idealFor: "M",
        rating: 4.2,
    },
    {
        _id: uuid(),
        name: "Men Checked Shirt4",
        alt: "mens shirt",
        brand: "Roadster",
        newPrice: 3719,
        oldPrice: 5699,
        discount: 45,
        size: "L",
        idealFor: "M",
        rating: 4.2,
    },
    {
        _id: uuid(),
        name: "Men Checked Shirt5",
        alt: "mens shirt",
        brand: "Roadster",
        newPrice: 1850,
        oldPrice: 2099,
        discount: 10,
        size: "L",
        idealFor: "M",
        rating: 4.2,
    },
    {
        _id: uuid(),
        name: "Men Checked Shirt6",
        alt: "mens shirt",
        brand: "Roadster",
        newPrice: 750,
        oldPrice: 3499,
        discount: 75,
        size: "L",
        idealFor: "M",
        rating: 4.2,
    },
    {
        _id: uuid(),
        name: "Men Checked Shirt7",
        alt: "mens shirt",
        brand: "Roadster",
        newPrice: 1564,
        oldPrice: 4789,
        discount: 80,
        size: "L",
        idealFor: "M",
        rating: 4.2,
    }
]